routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages/welcome');
});
Route::resource('/category','CategoryController');
Route::resource('/post','PostController');
Route::resource('/tag','TagController');

Route::get('/home', 'HomeController@index')->name('home');

resources/views/dashboard/category-create.blade.php
@extends('layouts.main')


@section('content')


<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form method="post" action={{route('category.store')}}>
                @csrf
                <div class="form-group">
                <label for="exampleInputEmail1">Category Name</label>
                <input type="text" class="form-control" name="categoryname" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?php if(!empty($categories[0]->name)){echo $categories[0]->name;} ?>" placeholder="Enter category name">
                <input type="hidden" name="cat_id" value="<?php if(!empty($categories[0]->id)){echo $categories[0]->id;} ?>">    
            </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        
    </div>
</div>

  @endsection

resources/views/dashboard/category.blade.php
@extends('layouts.main')
@section('stylesheet')
<link type="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link type="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" />
@endsection

@section('content')
@if(Session::has('message'))
<p class="alert alert-info">{{ Session::get('message') }}</p>
@endif


<hr>
<a href="/category/create" class="float-right">Create Category</a>
<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Category Name</th>
            <th>Created Date</th>
            <th>Edit Category</th>
            <th>Delete Category</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)
        <tr>
            <td>{{$category->name}}</td>
            <td>{{$category->created_at}}</td>
            <th><a href="/category/{{$category->id}}/edit">Edit</a></th>
            <th><form method="post" action={{route('category.store')}}>
                @csrf
              
                <input type="hidden" name="delete_row" value="yes">
                <input type="hidden" name="cat_id" value="<?php if(!empty($categories[0]->id)){echo $categories[0]->id;} ?>">    
  
                <button type="submit" class="btn btn-primary">Delete</button>
            </form></th>
        </tr>
       @endforeach
        
    </tbody>
    <tfoot>
        <tr>
            <th>Category Name</th>
            <th>Created Date</th>
            <th>Edit Category</th>
            <th>Delete Category</th>
        </tr>
    </tfoot>
</table>

@endsection

@section('script')
    <script src="https://code.jquery.com/jquery-3.3.1.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"  crossorigin="anonymous"></script>
@endsection

resources/views/dashboard/create-post.blade.php
@extends('layouts.main')
@section('stylesheet')

<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />

@endsection

@section('content')


<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form method="post" action={{route('post.store')}}>
                @csrf
                <div class="form-group">
                <label for="exampleInputEmail1">Post Name</label>
                <input type="text" class="form-control" name="postname" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?php if(!empty($posts[0]->name)){echo $posts[0]->name;} ?>" placeholder="Enter post name">
                <label for="exampleInputEmail1">Post Description</label>
                <textarea type="text" class="form-control" name="postdescription" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter post description"><?php if(!empty($posts[0]->description)){echo $posts[0]->description;} ?></textarea>
            <input type="hidden" name="post_id" value="<?php if(!empty($posts[0]->id)){echo $posts[0]->id;} ?>">    
            </div>
                <div class="input-group mb-3">
                    <select class="custom-select" id="inputGroupSelect02" name="categoryname">
                        <option selected>Choose...</option>
                        @foreach ($categories as $category)
                            <option <?php if(!empty($posts[0]->category_id) && $category->id == $posts[0]->category_id){ echo 'selected';} ?> value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                  </div>
                  <div class="input-group mb-3">
                      @if(empty($tags_array))
                      <select class="form-control" name="tag[]" multiple="multiple">
                        @foreach($tags as $tag)
                            <option value={{ $tag->id }}>{{$tag->name}}</option>
                        @endforeach
                    </select>

                      @else
                            <select class="form-control" name="tag[]" multiple="multiple">
                                @foreach($tags as $tag)
                                    <option   <?php if (in_array($tag->id , $tags_array))
                                    {
                                    echo 'selected="selected"';
                                    } ?>value={{ $tag->id }}>{{$tag->name}}</option>
                                @endforeach
                            </select>
                        @endif
                      
                  </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        
    </div>
</div>


  @endsection
  @section('script')
  <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        $(".js-example-tags").select2({
        tags: true
        });
    </script>
@endsection

resources/views/dashboard/post.blade.php
@extends('layouts.main')
@section('stylesheet')
<link type="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link type="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" />
@endsection

@section('content')
@if(Session::has('message'))
<p class="alert alert-info">{{ Session::get('message') }}</p>
@endif


<hr>
<a href="/post/create" class="float-right">Create Post</a>
<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Post Name</th>
            <th>Post Description</th>
            <th>Category Name</th>
            <th>Tag Name</th>
            <th>Created Date</th>
            <th>Edit Post</th>
            <th>Delete Post</th>
        </tr>
    </thead>
    <tbody>
        @foreach($posts as $key=>$post)
        <tr>
            <td>{{$post['name']}}</td>
            <td>{{$post['description']}}</td>
            <td>{{$post['category_name']}}</td>
            <td>
                <?php if(!empty($post['post_tag_data'])){ ?>
            @foreach($post['post_tag_data'] as $k=>$poststag)
                 {{$poststag}}<br/>
            @endforeach
                <?php } ?>
            </td>
            <td>{{$post['created_at']}}</td>
            <th><a href="/post/{{$post['id']}}/edit">Edit</a></th>
            <th><form method="post" action={{route('post.store')}}>
                @csrf
              
                <input type="hidden" name="delete_row" value="yes">
                <input type="hidden" name="post_id" value="<?php if(!empty($post['id'])){echo $post['id'];} ?>">    
  
                <button type="submit" class="btn btn-primary">Delete</button>
            </form></th>
        </tr>
       @endforeach
        
    </tbody>
    <tfoot>
        <tr>
            <th>Post Name</th>
            <th>Post Description</th>
            <th>Category Name</th>
            <th>Tag Name</th>
            <th>Created Date</th>
            <th>Edit Post</th>
            <th>Delete Post</th>
        </tr>
    </tfoot>
</table>

@endsection

@section('script')
    <script src="https://code.jquery.com/jquery-3.3.1.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"  crossorigin="anonymous"></script>
@endsection

resources/views/dashboard/tag-create.blade.php
@extends('layouts.main')


@section('content')


<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form method="post" action={{route('tag.store')}}>
                @csrf
                <div class="form-group">
                <label for="exampleInputEmail1">Tag Name</label>
                <input type="text" class="form-control" name="name" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?php if(!empty($tags[0]->name)){echo $tags[0]->name;} ?>" placeholder="Enter tag name">
                <input type="hidden" name="tag_id" value="<?php if(!empty($tags[0]->id)){echo $tags[0]->id;} ?>"> 
                  
            </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        
    </div>
</div>

  @endsection

resources/views/dashboard/tag.blade.php
@extends('layouts.main')
@section('stylesheet')
<link type="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link type="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" />
@endsection

@section('content')
@if(Session::has('message'))
<p class="alert alert-info">{{ Session::get('message') }}</p>
@endif


<hr>
<a href="/tag/create" class="float-right">Create Tag</a>
<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>tag Name</th>
            <th>Created Date</th>
            <th>Edit tag</th>
            <th>Delete tag</th>
        </tr>
    </thead>
    <tbody>
        @foreach($tags as $tag)
        <tr>
            <td>{{$tag->name}}</td>
            <td>{{$tag->created_at}}</td>
            <th><a href="/tag/{{$tag->id}}/edit">Edit</a></th>
            <th><form method="post" action={{route('tag.store')}}>
                @csrf
              
                <input type="hidden" name="delete_row" value="yes">
                <input type="hidden" name="tag_id" value="<?php if(!empty($tag->id)){echo $tag->id;} ?>">    
  
                <button type="submit" class="btn btn-primary">Delete</button>
            </form></th>
        </tr>
       @endforeach
        
    </tbody>
    <tfoot>
        <tr>
            <th>tag Name</th>
            <th>Created Date</th>
            <th>Edit tag</th>
            <th>Delete tag</th>
        </tr>
    </tfoot>
</table>

@endsection

@section('script')
    <script src="https://code.jquery.com/jquery-3.3.1.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"  crossorigin="anonymous"></script>
@endsection